# PARTE 2: DATOS SEMÁNTICOS

Autores:

Luisa Yánez Gutiérrez 

Miguel García Sánchez

In [1]:
#!pip install pandas
import pandas as pd

Fecha de descarga de datos: 1/08/22

In [2]:
datos_aire = pd.read_csv('calidad_aire_datos_meteo_mes.csv', sep=';')
datos_aire.head(25)

,provincia,municipio,estacion,magnitud,punto_muestreo,ano,mes,dia,h01,v01,...,h20,v20,h21,v21,h22,v22,h23,v23,h24,v24
0,28,102,1,81,28102001_81_89,2022,7,1,"6,0",V,...,"37,0",V,"42,0",V,"47,0",V,"55,0",V,"42,0",V
1,28,102,1,82,28102001_82_89,2022,7,1,"84,0",V,...,"149,0",V,"140,0",V,"156,0",V,"183,0",V,"216,0",V
2,28,102,1,83,28102001_83_89,2022,7,1,"149,0",V,...,"279,0",V,"259,0",V,"247,0",V,"229,0",V,"208,0",V
3,28,102,1,86,28102001_86_89,2022,7,1,"58,0",V,...,"31,0",V,"40,0",V,"44,0",V,"59,0",V,"72,0",V
4,28,102,1,87,28102001_87_89,2022,7,1,"924,0",V,...,"923,0",V,"924,0",V,"924,0",V,"925,0",V,"925,0",V
5,28,102,1,88,28102001_88_89,2022,7,1,"15,0",V,...,"43,0",V,"16,0",V,"16,0",V,"16,0",V,"15,0",V
6,28,102,1,89,28102001_89_89,2022,7,1,"0,0",V,...,"0,0",V,"0,0",V,"0,0",V,"0,0",V,"0,0",V
7,28,120,1,81,28120001_81_89,2022,7,1,"12,0",V,...,"9,0",V,"17,0",V,"18,0",V,"18,0",V,"15,0",V
8,28,120,1,82,28120001_82_89,2022,7,1,"35,0",V,...,"30,0",V,"35,0",V,"35,0",V,"91,0",V,"170,0",V
9,28,120,1,83,28120001_83_89,2022,7,1,"89,0",V,...,"166,0",V,"155,0",V,"157,0",V,"162,0",V,"163,0",V
10,28,120,1,86,28120001_86_89,2022,7,1,"60,0",V,...,"42,0",V,"45,0",V,"48,0",V,"49,0",V,"67,0",V
11,28,120,1,87,28120001_87_89,2022,7,1,"814,0",V,...,"816,0",V,"816,0",V,"817,0",V,"817,0",V,"817,0",V
12,28,120,1,88,28120001_88_89,2022,7,1,"1,0",V,...,"11,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V
13,28,120,1,89,28120001_89_89,2022,7,1,"0,0",V,...,"0,0",V,"0,0",V,"0,0",V,"0,0",V,"0,0",V
14,28,123,2,81,28123002_81_89,2022,7,1,"42,0",V,...,"7,0",V,"13,0",V,"2,0",V,"35,0",V,"32,0",V
15,28,123,2,82,28123002_82_89,2022,7,1,"50,0",V,...,"12,0",V,"71,0",V,"148,0",V,"154,0",V,"136,0",V
16,28,123,2,83,28123002_83_89,2022,7,1,"189,0",V,...,"344,0",V,"319,0",V,"311,0",V,"295,0",V,"272,0",V
17,28,123,2,86,28123002_86_89,2022,7,1,"51,0",V,...,"27,0",V,"32,0",V,"40,0",V,"47,0",V,"57,0",V
18,28,123,2,87,28123002_87_89,2022,7,1,"949,0",V,...,"947,0",V,"948,0",V,"948,0",V,"949,0",V,"949,0",V
19,28,123,2,88,28123002_88_89,2022,7,1,"2,0",V,...,"25,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V
20,28,123,2,89,28123002_89_89,2022,7,1,"0,0",V,...,"0,0",V,"0,0",V,"0,0",V,"0,0",V,"0,0",V
21,28,13,2,81,28013002_81_89,2022,7,1,"14,0",V,...,"8,0",V,"15,0",V,"26,0",V,"28,0",V,"38,0",V
22,28,13,2,82,28013002_82_89,2022,7,1,"71,0",V,...,"104,0",V,"134,0",V,"147,0",V,"135,0",V,"91,0",V
23,28,13,2,83,28013002_83_89,2022,7,1,"208,0",V,...,"339,0",V,"316,0",V,"297,0",V,"274,0",V,"253,0",V
24,28,13,2,86,28013002_86_89,2022,7,1,"41,0",V,...,"25,0",V,"35,0",V,"42,0",V,"51,0",V,"60,0",V

Cambiamos los tipos de algunas variables y en algunas de ellas añadimos ceros en el caso en que las varibales no tengan 3 dígitos.

In [3]:
datos_aire['provincia'] = pd.Series(datos_aire['provincia']).astype(str)
datos_aire['municipio'] = pd.Series(datos_aire['municipio']).astype(str).str.zfill(3)
datos_aire['estacion'] = pd.Series(datos_aire['estacion']).astype(str).str.zfill(3)
datos_aire['estacion_codigo'] = datos_aire['provincia'] + datos_aire['municipio'] + datos_aire['estacion']
datos_aire['magnitud'] = pd.Series(datos_aire['magnitud']).astype(str)
datos_aire.head()

,provincia,municipio,estacion,magnitud,punto_muestreo,ano,mes,dia,h01,v01,...,v20,h21,v21,h22,v22,h23,v23,h24,v24,estacion_codigo
0,28,102,001,81,28102001_81_89,2022,7,1,"6,0",V,...,V,"42,0",V,"47,0",V,"55,0",V,"42,0",V,28102001
1,28,102,001,82,28102001_82_89,2022,7,1,"84,0",V,...,V,"140,0",V,"156,0",V,"183,0",V,"216,0",V,28102001
2,28,102,001,83,28102001_83_89,2022,7,1,"149,0",V,...,V,"259,0",V,"247,0",V,"229,0",V,"208,0",V,28102001
3,28,102,001,86,28102001_86_89,2022,7,1,"58,0",V,...,V,"40,0",V,"44,0",V,"59,0",V,"72,0",V,28102001
4,28,102,001,87,28102001_87_89,2022,7,1,"924,0",V,...,V,"924,0",V,"924,0",V,"925,0",V,"925,0",V,28102001

Movemos la variable estacion_codigo a la primera posición

In [4]:
estacion_codigo= datos_aire['estacion_codigo']
#estacion_codigo.head()
datos_aire=datos_aire.drop(['estacion_codigo'], axis=1)
datos_aire.insert(0,'estacion_codigo',estacion_codigo)
datos_aire = datos_aire.sort_values(by=['estacion_codigo'], ascending=True)
datos_aire.head()

,estacion_codigo,provincia,municipio,estacion,magnitud,punto_muestreo,ano,mes,dia,h01,...,h20,v20,h21,v21,h22,v22,h23,v23,h24,v24
770,28005002,28,005,002,81,28005002_81_89,2022,7,5,"13,0",...,"4,0",V,"7,0",V,"15,0",V,"23,0",V,"26,0",V
3458,28005002,28,005,002,81,28005002_81_89,2022,7,21,"7,0",...,"2,0",V,"2,0",V,"12,0",V,"18,0",V,"27,0",V
3795,28005002,28,005,002,82,28005002_82_89,2022,7,23,"43,0",...,"242,0",V,"123,0",V,"131,0",V,"118,0",V,"108,0",V
602,28005002,28,005,002,81,28005002_81_89,2022,7,4,"4,0",...,"3,0",V,"2,0",V,"2,0",V,"2,0",V,"4,0",V
603,28005002,28,005,002,82,28005002_82_89,2022,7,4,"110,0",...,"252,0",V,"154,0",V,"128,0",V,"101,0",V,"59,0",V

Cargamos los datos del CSV calidad_aire_estaciones y seleccionamos las tres variables que se nos indica en la práctica (datos de nombre de la estación, latitud y longitud (UTM))

In [5]:
nombres_colum = ['estacion_codigo', 'estacion_coord_UTM_ETRS89_x', 'estacion_coord_UTM_ETRS89_y']
datos_estaciones = pd.read_csv('calidad_aire_estaciones.csv', sep=';', encoding='latin-1', usecols=nombres_colum)
datos_estaciones['estacion_codigo'] = pd.Series(datos_estaciones['estacion_codigo']).astype(str)
datos_estaciones.head()

  estacion_codigo  estacion_coord_UTM_ETRS89_x  estacion_coord_UTM_ETRS89_y
0        28005002                       467979                      4481011
1        28006004                       445363                      4487950
2        28007004                       429190                      4466041
3        28009001                       457418                      4494449
4        28013002                       449541                      4431618

Juntamos los ficheros csv uniendolos a través de la columna "estacion_codigo".

Creamos la variable date_observation la cual esta formada por punto_muestreo, año, mes y día. Movemos la variable date_observation a la primera posición.

In [6]:
df_aire_esta= pd.merge(datos_aire, datos_estaciones, how="left", on="estacion_codigo")
df_aire_esta['date_observation'] = pd.Series(df_aire_esta['punto_muestreo']).astype(str)+pd.Series(df_aire_esta['ano']).astype(str) + pd.Series(df_aire_esta['mes']).astype(str).str.zfill(2) + pd.Series(df_aire_esta['dia']).astype(str).str.zfill(2)
date_observation= df_aire_esta['date_observation']
df_aire_esta=df_aire_esta.drop(['date_observation'], axis=1)
df_aire_esta.insert(0,'date_observation',date_observation)
df_aire_esta = df_aire_esta.sort_values(by=['estacion_codigo'], ascending=True)
df_aire_esta.head()

,date_observation,estacion_codigo,provincia,municipio,estacion,magnitud,punto_muestreo,ano,mes,dia,...,h21,v21,h22,v22,h23,v23,h24,v24,estacion_coord_UTM_ETRS89_x,estacion_coord_UTM_ETRS89_y
0,28005002_81_8920220705,28005002,28,005,002,81,28005002_81_89,2022,7,5,...,"7,0",V,"15,0",V,"23,0",V,"26,0",V,467979,4481011
138,28005002_86_8920220705,28005002,28,005,002,86,28005002_86_89,2022,7,5,...,"21,0",V,"43,0",V,"49,0",V,"55,0",V,467979,4481011
139,28005002_87_8920220705,28005002,28,005,002,87,28005002_87_89,2022,7,5,...,"950,0",V,"950,0",V,"951,0",V,"951,0",V,467979,4481011
140,28005002_88_8920220705,28005002,28,005,002,88,28005002_88_89,2022,7,5,...,"0,0",V,"0,0",V,"0,0",V,"0,0",V,467979,4481011
141,28005002_89_8920220705,28005002,28,005,002,89,28005002_89_89,2022,7,5,...,"0,0",V,"0,0",V,"0,0",V,"0,0",V,467979,4481011

In [7]:
df_aire_esta.dtypes

date_observation               object
estacion_codigo                object
provincia                      object
municipio                      object
estacion                       object
magnitud                       object
punto_muestreo                 object
ano                             int64
mes                             int64
dia                             int64
h01                            object
v01                            object
h02                            object
v02                            object
h03                            object
v03                            object
h04                            object
v04                            object
h05                            object
v05                            object
h06                            object
v06                            object
h07                            object
v07                            object
h08                            object
v08                            object
h09                            object
v09                            object
h10                            object
v10                            object
h11                            object
v11                            object
h12                            object
v12                            object
h13                            object
v13                            object
h14                            object
v14                            object
h15                            object
v15                            object
h16                            object
v16                            object
h17                            object
v17                            object
h18                            object
v18                            object
h19                            object
v19                            object
h20                            object
v20                            object
h21                            object
v21                            object
h22                            object
v22                            object
h23                            object
v23                            object
h24                            object
v24                            object
estacion_coord_UTM_ETRS89_x     int64
estacion_coord_UTM_ETRS89_y     int64
dtype: object

# Conjunto de datos semánticamente anotados

In [8]:
#!pip install rdflib
from rdflib import Graph, Literal, URIRef, BNode
from rdflib.namespace import RDF, FOAF

Creamos un grafo vacío

In [9]:
g = Graph()

Definimos los predicados que usaremos en las tripletas

In [10]:
has_punto_muestreo = URIRef('http://www.ontologies.org/has_punto_muestreo')
has_latitude  = URIRef("http://www.w3.org/2003/01/geo/wgs84_pos#lat")
has_longitude = URIRef('http://www.w3.org/2003/01/geo/wgs84_pos#long')
has_provincia = URIRef('http://www.ontologies.org/has_provincia')
has_municipio = URIRef('http://www.ontologies.org/has_municipio')
has_estacion = URIRef('http://www.ontologies.org/has_estacion')
has_ano = URIRef('http://www.ontologies.org/has_ano')
has_mes = URIRef('http://www.ontologies.org/has_mes')
has_dia = URIRef('http://www.ontologies.org/has_dia')
has_magnitud = URIRef('http://www.ontologies.org/has_magnitud')
has_date_observation = URIRef('http://www.ontologies.org/has_observation')
has_h01 = URIRef('http://www.ontologies.org/has_h01')
has_v01 = URIRef('http://www.ontologies.org/has_v01')
has_h02 = URIRef('http://www.ontologies.org/has_h02')
has_v02 = URIRef('http://www.ontologies.org/has_v02')
has_h03 = URIRef('http://www.ontologies.org/has_h03')
has_v03 = URIRef('http://www.ontologies.org/has_v03')
has_h04 = URIRef('http://www.ontologies.org/has_h04')
has_v04 = URIRef('http://www.ontologies.org/has_v04')
has_h05 = URIRef('http://www.ontologies.org/has_h05')
has_v05 = URIRef('http://www.ontologies.org/has_v05')
has_h06 = URIRef('http://www.ontologies.org/has_h06')
has_v06 = URIRef('http://www.ontologies.org/has_v06')
has_h07 = URIRef('http://www.ontologies.org/has_h07')
has_v07 = URIRef('http://www.ontologies.org/has_v07')
has_h08 = URIRef('http://www.ontologies.org/has_h08')
has_v08 = URIRef('http://www.ontologies.org/has_v08')
has_h09 = URIRef('http://www.ontologies.org/has_h09')
has_v09 = URIRef('http://www.ontologies.org/has_v09')
has_h10 = URIRef('http://www.ontologies.org/has_h10')
has_v10 = URIRef('http://www.ontologies.org/has_v10')
has_h11 = URIRef('http://www.ontologies.org/has_h11')
has_v11 = URIRef('http://www.ontologies.org/has_v11')
has_h12 = URIRef('http://www.ontologies.org/has_h12')
has_v12 = URIRef('http://www.ontologies.org/has_v12')
has_h13 = URIRef('http://www.ontologies.org/has_h13')
has_v13 = URIRef('http://www.ontologies.org/has_v13')
has_h14 = URIRef('http://www.ontologies.org/has_h14')
has_v14 = URIRef('http://www.ontologies.org/has_v14')
has_h15 = URIRef('http://www.ontologies.org/has_h15')
has_v15 = URIRef('http://www.ontologies.org/has_v15')
has_h16 = URIRef('http://www.ontologies.org/has_h16')
has_v16 = URIRef('http://www.ontologies.org/has_v16')
has_h17 = URIRef('http://www.ontologies.org/has_h17')
has_v17 = URIRef('http://www.ontologies.org/has_v17')
has_h18 = URIRef('http://www.ontologies.org/has_h18')
has_v18 = URIRef('http://www.ontologies.org/has_v18')
has_h19 = URIRef('http://www.ontologies.org/has_h19')
has_v19 = URIRef('http://www.ontologies.org/has_v19')
has_h20 = URIRef('http://www.ontologies.org/has_h20')
has_v20 = URIRef('http://www.ontologies.org/has_v20')
has_h21 = URIRef('http://www.ontologies.org/has_h21')
has_v21 = URIRef('http://www.ontologies.org/has_v21')
has_h22 = URIRef('http://www.ontologies.org/has_h22')
has_v22 = URIRef('http://www.ontologies.org/has_v22')
has_h23 = URIRef('http://www.ontologies.org/has_h23')
has_v23 = URIRef('http://www.ontologies.org/has_v23')
has_h24 = URIRef('http://www.ontologies.org/has_h24')
has_v24 = URIRef('http://www.ontologies.org/has_v24')

Definimos las URIs de los municipios utilizando los recuersos de la dbpedia.

In [11]:
dic_municipios= {'005':'https://dbpedia.org/page/Alcal%C3%A1_de_Henares', 
                 '006':'https://dbpedia.org/page/Alcobendas', 
                 '007':'https://dbpedia.org/page/Alcorc%C3%B3n', 
                 '009':'https://dbpedia.org/page/Algete', 
                 '013':'https://dbpedia.org/page/Aranjuez', 
                 '014':'https://dbpedia.org/page/Arganda_del_Rey', 
                 '016':'https://dbpedia.org/page/El_Atazar', 
                 '045':'https://dbpedia.org/page/Colmenar_Viejo', 
                 '047':'https://dbpedia.org/page/Collado_Villalba', 
                 '049':'https://dbpedia.org/page/Coslada', 
                 '058':'https://dbpedia.org/page/Fuenlabrada', 
                 '065':'https://dbpedia.org/page/Getafe', 
                 '067':'https://dbpedia.org/page/Guadalix_de_la_Sierra', 
                 '074':'https://dbpedia.org/page/Legan%C3%A9s', 
                 '080':'https://dbpedia.org/page/Majadahonda', 
                 '092':'https://dbpedia.org/page/M%C3%B3stoles', 
                 '102':'https://dbpedia.org/page/Orusco_de_Taju%C3%B1a',
                 '120':'https://es.dbpedia.org/page/Estaci%C3%B3n_de_Dos_Castillas_(Cercan%C3%ADas_Madrid)', 
                 '123':'https://dbpedia.org/page/Rivas-Vaciamadrid', 
                 '133':'https://dbpedia.org/page/San_Mart%C3%ADn_de_Valdeiglesias', 
                 '148':'https://dbpedia.org/page/Torrej%C3%B3n_de_Ardoz', 
                 '161':'https://dbpedia.org/page/Valdemoro', 
                 '171':'https://dbpedia.org/page/Villa_del_Prado',
                 '180':'https://dbpedia.org/page/Villarejo_de_Salvan%C3%A9s'}

Generamos el grafo RDF definiendo los datos semánticos anotados en tripletas.

In [12]:
for index, row in df_aire_esta.iterrows():
    estacion_codigo= URIRef(row['estacion_codigo'])
    date_observation = URIRef(row['date_observation'])
    punto_muestreo= URIRef(row['punto_muestreo'])
    g.add((estacion_codigo, has_provincia, Literal(row['provincia'])))
    if row['municipio'] in dic_municipios.keys():
        key= row['municipio']
        val= dic_municipios[key]
        uri_municipio=URIRef(val)
        g.add((estacion_codigo, has_municipio,uri_municipio))

    g.add((estacion_codigo, has_estacion, Literal(row['estacion'])))
    g.add((estacion_codigo, has_latitude, Literal(row['estacion_coord_UTM_ETRS89_x'])))
    g.add((estacion_codigo, has_longitude, Literal(row['estacion_coord_UTM_ETRS89_y'])))
    g.add((estacion_codigo, has_punto_muestreo, punto_muestreo))
    g.add((punto_muestreo, has_magnitud, Literal(row['magnitud'])))
    g.add((punto_muestreo, has_date_observation, date_observation)) # date (punto_muestreo + fecha)
    g.add((date_observation, has_h01, Literal(row['h01']))) 
    g.add((date_observation, has_v01, Literal(row['v01'])))
    g.add((date_observation, has_h01, Literal(row['h02']))) 
    g.add((date_observation, has_v01, Literal(row['v02'])))
    g.add((date_observation, has_h01, Literal(row['h03']))) 
    g.add((date_observation, has_v01, Literal(row['v03'])))
    g.add((date_observation, has_h01, Literal(row['h04']))) 
    g.add((date_observation, has_v01, Literal(row['v04'])))
    g.add((date_observation, has_h01, Literal(row['h05']))) 
    g.add((date_observation, has_v01, Literal(row['v05'])))
    g.add((date_observation, has_h01, Literal(row['h06']))) 
    g.add((date_observation, has_v01, Literal(row['v06'])))
    g.add((date_observation, has_h01, Literal(row['h07']))) 
    g.add((date_observation, has_v01, Literal(row['v07'])))
    g.add((date_observation, has_h01, Literal(row['h08']))) 
    g.add((date_observation, has_v01, Literal(row['v08'])))
    g.add((date_observation, has_h01, Literal(row['h09']))) 
    g.add((date_observation, has_v01, Literal(row['v09'])))
    g.add((date_observation, has_h01, Literal(row['h10']))) 
    g.add((date_observation, has_v01, Literal(row['v10'])))
    g.add((date_observation, has_h01, Literal(row['h11']))) 
    g.add((date_observation, has_v01, Literal(row['v11'])))
    g.add((date_observation, has_h01, Literal(row['h12']))) 
    g.add((date_observation, has_v01, Literal(row['v12'])))
    g.add((date_observation, has_h01, Literal(row['h13']))) 
    g.add((date_observation, has_v01, Literal(row['v13'])))
    g.add((date_observation, has_h01, Literal(row['h14']))) 
    g.add((date_observation, has_v01, Literal(row['v14'])))
    g.add((date_observation, has_h01, Literal(row['h15']))) 
    g.add((date_observation, has_v01, Literal(row['v15'])))
    g.add((date_observation, has_h01, Literal(row['h16']))) 
    g.add((date_observation, has_v01, Literal(row['v16'])))
    g.add((date_observation, has_h01, Literal(row['h17']))) 
    g.add((date_observation, has_v01, Literal(row['v17'])))
    g.add((date_observation, has_h01, Literal(row['h18']))) 
    g.add((date_observation, has_v01, Literal(row['v18'])))
    g.add((date_observation, has_h01, Literal(row['h19']))) 
    g.add((date_observation, has_v01, Literal(row['v19'])))
    g.add((date_observation, has_h01, Literal(row['h20']))) 
    g.add((date_observation, has_v01, Literal(row['v20'])))
    g.add((date_observation, has_h01, Literal(row['h21']))) 
    g.add((date_observation, has_v01, Literal(row['v21'])))
    g.add((date_observation, has_h01, Literal(row['h22']))) 
    g.add((date_observation, has_v01, Literal(row['v22'])))
    g.add((date_observation, has_h01, Literal(row['h23']))) 
    g.add((date_observation, has_v01, Literal(row['v23'])))
    g.add((date_observation, has_h01, Literal(row['h24']))) 
    g.add((date_observation, has_v01, Literal(row['v24'])))
    g.add((date_observation, has_ano, Literal(row['ano'])))
    g.add((date_observation, has_mes, Literal(row['mes'])))
    g.add((date_observation, has_dia, Literal(row['dia'])))
    
    
g.serialize(destination ="datossemanticos.rdf", format = "xml")
print("generado")

generado